spring:
    profiles:
        active: "dev"
        include: swagger
    datasource:
        url: 'jdbc:mysql://localhost:3306/'
        username: root
        password:
        driver: com.mysql.jdbc.Driver
        hikari:
            minIdle: 10
            idle-timeout: 10000
            maximumPoolSize: 30
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        database-platform:
        database: MySQL
        show-sql: true
    mail:
        default-encoding: UTF-8
        host:
        username:
        password:
        port: 25
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        protocol: smtp
        test-connection: false
social:
    twitter:
        consumerKey:
        consumerSecret:
        accessToken:
        accessTokenSecret:



